### ISSUE TITLE
admission.work.open-cluster-management.io/v1: the server is currently unable to handle the request

### ISSUE THREAD

**Issue by sangshenya** [open-cluster-management-io/config-policy-controller#11]
config-policy-controller pod logs:

Available policies in namespaces: 
configpolicy policy-pod-example in namespace(s) [default]
I0812 07:10:59.654954       1 request.go:655] Throttling request took 1.04867382s, request: GET:https://10.1.0.1:443/apis/extensions/v1beta1?timeout=32s
E0812 07:11:00.956418       1 configurationpolicy_controller.go:211] Failed to retrieve apiresourcelist with err: unable to retrieve the complete list of server APIs: admission.cluster.open-cluster-management.io/v1: the server is currently unable to handle the request, admission.work.open-cluster-management.io/v1: the server is currently unable to handle the request
E0812 07:11:05.855787       1 configurationpolicy_controller.go:221] Unexpected failure detected. You api server might not be stable. Waiting for next loop...

**Comment by dhaiducek** [comment]
@sangshenya I'm embarrassed this issue went unaddressed for so long--I apologize for that. Is this still an issue?
